# 서버 포트 설정
server:
  port: 8082

# database 연동 설정
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: testuser
#    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    database: postgresql